import productImg1 from "../../assets/product1.jpg";
import productImg2 from "../../assets/product2.jpg";
import productImg3 from "../../assets/product3.jpg";
import productImg4 from "../../assets/product4.jpg";
import productImg5 from "../../assets/product5.jpg";
import productImg6 from "../../assets/product6.jpg";
import productImg7 from "../../assets/product7.jpg";
import productImg8 from "../../assets/product8.jpg";

const products = [
  {
    id: 1,
    name: "Sample Product",
    image: productImg1,
    rating: 5,
    originalPrice: 1650,
    discountPrice: 1320,
    discount: 20,
  },
  {
    id: 2,
    name: "Sample Product",
    image: productImg2,
    rating: 5,
    originalPrice: 2050,
    discountPrice: 1640,
    discount: 20,
  },
  {
    id: 3,
    name: "Sample Product",
    image: productImg3,
    rating: 5,
    originalPrice: 1450,
    discountPrice: 1160,
    discount: 20,
  },
  {
    id: 4,
    name: "Sample Product",
    image: productImg4,
    rating: 5,
    originalPrice: 3500,
    discountPrice: 2800,
    discount: 20,
  },
  {
    id: 5,
    name: "Sample Product No Discount",
    image: productImg5,
    rating: 4,
    originalPrice: 1000,
    discountPrice: 1000,
    discount: 0,
  },
  {
    id: 6,
    name: "Sample Product No Discount",
    image: productImg6,
    rating: 4,
    originalPrice: 1000,
    discountPrice: 1000,
    discount: 0,
  },
  {
    id: 7,
    name: "Sample Product No Discount",
    image: productImg7,
    rating: 4,
    originalPrice: 1000,
    discountPrice: 1000,
    discount: 0,
  },
  {
    id: 8,
    name: "Sample Product No Discount",
    image: productImg8,
    rating: 4,
    originalPrice: 1000,
    discountPrice: 1000,
    discount: 0,
  },
   {
    id: 9,
    name: "Sample Product No Discount",
    image: productImg1,
    rating: 4,
    originalPrice: 1000,
    discountPrice: 1000,
    discount: 0,
  },
   {
    id: 10,
    name: "Sample Product No Discount",
    image: productImg2,
    rating: 4,
    originalPrice: 1000,
    discountPrice: 1000,
    discount: 0,
  },
   {
    id: 11,
    name: "Sample Product No Discount",
    image: productImg3,
    rating: 4,
    originalPrice: 1000,
    discountPrice: 1000,
    discount: 0,
  },
   {
    id: 12,
    name: "Sample Product No Discount",
    image: productImg4,
    rating: 4,
    originalPrice: 1000,
    discountPrice: 1000,
    discount: 0,
  },
    {
    id: 13,
    name: "Sample Product No Discount",
    image: productImg5,
    rating: 4,
    originalPrice: 1000,
    discountPrice: 1000,
    discount: 0,
  },
   {
    id: 14,
    name: "Sample Product No Discount",
    image: productImg6,
    rating: 4,
    originalPrice: 1000,
    discountPrice: 1000,
    discount: 0,
  },
   {
    id: 15,
    name: "Sample Product No Discount",
    image: productImg7,
    rating: 4,
    originalPrice: 1000,
    discountPrice: 1000,
    discount: 0,
  },
   {
    id: 16,
    name: "Sample Product No Discount",
    image: productImg8,
    rating: 4,
    originalPrice: 1000,
    discountPrice: 1000,
    discount: 0,
  },
  {
    id: 17,
    name: "Sample Product No Discount",
    image: productImg1,
    rating: 4,
    originalPrice: 1000,
    discountPrice: 1000,
    discount: 0,
  },
  {
    id: 18,
    name: "Sample Product No Discount",
    image: productImg2,
    rating: 4,
    originalPrice: 1000,
    discountPrice: 1000,
    discount: 0,
  },
  {
    id: 19,
    name: "Sample Product No Discount",
    image: productImg3,
    rating: 4,
    originalPrice: 1000,
    discountPrice: 1000,
    discount: 0,
  },
  {
    id: 20,
    name: "Sample Product No Discount",
    image: productImg4,
    rating: 4,
    originalPrice: 1000,
    discountPrice: 1000,
    discount: 0,
  },
  {
    id: 21,
    name: "Sample Product No Discount",
    image: productImg5,
    rating: 4,
    originalPrice: 1000,
    discountPrice: 1000,
    discount: 0,
  },
  {
    id: 22,
    name: "Sample Product No Discount",
    image: productImg6,
    rating: 4,
    originalPrice: 1000,
    discountPrice: 1000,
    discount: 0,
  },
  {
    id: 23,
    name: "Sample Product No Discount",
    image: productImg7,
    rating: 4,
    originalPrice: 1000,
    discountPrice: 1000,
    discount: 0,
  },
  {
    id: 24,
    name: "Sample Product No Discount",
    image: productImg8,
    rating: 4,
    originalPrice: 1000,
    discountPrice: 1000,
    discount: 0,
  },
];

export default products;
